# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.6

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/tinganho/Development/l10ns

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/tinganho/Development/l10ns

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/tinganho/Development/l10ns/CMakeFiles /Users/tinganho/Development/l10ns/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/tinganho/Development/l10ns/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named accept-baseline

# Build rule for target.
accept-baseline: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 accept-baseline
.PHONY : accept-baseline

# fast build rule for target.
accept-baseline/fast:
	$(MAKE) -f CMakeFiles/accept-baseline.dir/build.make CMakeFiles/accept-baseline.dir/build
.PHONY : accept-baseline/fast

#=============================================================================
# Target rules for targets named l10ns

# Build rule for target.
l10ns: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 l10ns
.PHONY : l10ns

# fast build rule for target.
l10ns/fast:
	$(MAKE) -f CMakeFiles/l10ns.dir/build.make CMakeFiles/l10ns.dir/build
.PHONY : l10ns/fast

#=============================================================================
# Target rules for targets named run-tests

# Build rule for target.
run-tests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 run-tests
.PHONY : run-tests

# fast build rule for target.
run-tests/fast:
	$(MAKE) -f CMakeFiles/run-tests.dir/build.make CMakeFiles/run-tests.dir/build
.PHONY : run-tests/fast

#=============================================================================
# Target rules for targets named generate-diagnostics

# Build rule for target.
generate-diagnostics: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 generate-diagnostics
.PHONY : generate-diagnostics

# fast build rule for target.
generate-diagnostics/fast:
	$(MAKE) -f CMakeFiles/generate-diagnostics.dir/build.make CMakeFiles/generate-diagnostics.dir/build
.PHONY : generate-diagnostics/fast

#=============================================================================
# Target rules for targets named find

# Build rule for target.
find: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 find
.PHONY : find

# fast build rule for target.
find/fast:
	$(MAKE) -f Source/Vendors/Glob/CMakeFiles/find.dir/build.make Source/Vendors/Glob/CMakeFiles/find.dir/build
.PHONY : find/fast

#=============================================================================
# Target rules for targets named glob

# Build rule for target.
glob: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 glob
.PHONY : glob

# fast build rule for target.
glob/fast:
	$(MAKE) -f Source/Vendors/Glob/CMakeFiles/glob.dir/build.make Source/Vendors/Glob/CMakeFiles/glob.dir/build
.PHONY : glob/fast

Source/Program/Exec.o: Source/Program/Exec.cpp.o

.PHONY : Source/Program/Exec.o

# target to build an object file
Source/Program/Exec.cpp.o:
	$(MAKE) -f CMakeFiles/l10ns.dir/build.make CMakeFiles/l10ns.dir/Source/Program/Exec.cpp.o
.PHONY : Source/Program/Exec.cpp.o

Source/Program/Exec.i: Source/Program/Exec.cpp.i

.PHONY : Source/Program/Exec.i

# target to preprocess a source file
Source/Program/Exec.cpp.i:
	$(MAKE) -f CMakeFiles/l10ns.dir/build.make CMakeFiles/l10ns.dir/Source/Program/Exec.cpp.i
.PHONY : Source/Program/Exec.cpp.i

Source/Program/Exec.s: Source/Program/Exec.cpp.s

.PHONY : Source/Program/Exec.s

# target to generate assembly for a file
Source/Program/Exec.cpp.s:
	$(MAKE) -f CMakeFiles/l10ns.dir/build.make CMakeFiles/l10ns.dir/Source/Program/Exec.cpp.s
.PHONY : Source/Program/Exec.cpp.s

Source/TestFramework/Exec.o: Source/TestFramework/Exec.cpp.o

.PHONY : Source/TestFramework/Exec.o

# target to build an object file
Source/TestFramework/Exec.cpp.o:
	$(MAKE) -f CMakeFiles/run-tests.dir/build.make CMakeFiles/run-tests.dir/Source/TestFramework/Exec.cpp.o
.PHONY : Source/TestFramework/Exec.cpp.o

Source/TestFramework/Exec.i: Source/TestFramework/Exec.cpp.i

.PHONY : Source/TestFramework/Exec.i

# target to preprocess a source file
Source/TestFramework/Exec.cpp.i:
	$(MAKE) -f CMakeFiles/run-tests.dir/build.make CMakeFiles/run-tests.dir/Source/TestFramework/Exec.cpp.i
.PHONY : Source/TestFramework/Exec.cpp.i

Source/TestFramework/Exec.s: Source/TestFramework/Exec.cpp.s

.PHONY : Source/TestFramework/Exec.s

# target to generate assembly for a file
Source/TestFramework/Exec.cpp.s:
	$(MAKE) -f CMakeFiles/run-tests.dir/build.make CMakeFiles/run-tests.dir/Source/TestFramework/Exec.cpp.s
.PHONY : Source/TestFramework/Exec.cpp.s

Tasks/AcceptBaseline.o: Tasks/AcceptBaseline.cpp.o

.PHONY : Tasks/AcceptBaseline.o

# target to build an object file
Tasks/AcceptBaseline.cpp.o:
	$(MAKE) -f CMakeFiles/accept-baseline.dir/build.make CMakeFiles/accept-baseline.dir/Tasks/AcceptBaseline.cpp.o
.PHONY : Tasks/AcceptBaseline.cpp.o

Tasks/AcceptBaseline.i: Tasks/AcceptBaseline.cpp.i

.PHONY : Tasks/AcceptBaseline.i

# target to preprocess a source file
Tasks/AcceptBaseline.cpp.i:
	$(MAKE) -f CMakeFiles/accept-baseline.dir/build.make CMakeFiles/accept-baseline.dir/Tasks/AcceptBaseline.cpp.i
.PHONY : Tasks/AcceptBaseline.cpp.i

Tasks/AcceptBaseline.s: Tasks/AcceptBaseline.cpp.s

.PHONY : Tasks/AcceptBaseline.s

# target to generate assembly for a file
Tasks/AcceptBaseline.cpp.s:
	$(MAKE) -f CMakeFiles/accept-baseline.dir/build.make CMakeFiles/accept-baseline.dir/Tasks/AcceptBaseline.cpp.s
.PHONY : Tasks/AcceptBaseline.cpp.s

Tasks/GenerateDiagnostics.o: Tasks/GenerateDiagnostics.cpp.o

.PHONY : Tasks/GenerateDiagnostics.o

# target to build an object file
Tasks/GenerateDiagnostics.cpp.o:
	$(MAKE) -f CMakeFiles/generate-diagnostics.dir/build.make CMakeFiles/generate-diagnostics.dir/Tasks/GenerateDiagnostics.cpp.o
.PHONY : Tasks/GenerateDiagnostics.cpp.o

Tasks/GenerateDiagnostics.i: Tasks/GenerateDiagnostics.cpp.i

.PHONY : Tasks/GenerateDiagnostics.i

# target to preprocess a source file
Tasks/GenerateDiagnostics.cpp.i:
	$(MAKE) -f CMakeFiles/generate-diagnostics.dir/build.make CMakeFiles/generate-diagnostics.dir/Tasks/GenerateDiagnostics.cpp.i
.PHONY : Tasks/GenerateDiagnostics.cpp.i

Tasks/GenerateDiagnostics.s: Tasks/GenerateDiagnostics.cpp.s

.PHONY : Tasks/GenerateDiagnostics.s

# target to generate assembly for a file
Tasks/GenerateDiagnostics.cpp.s:
	$(MAKE) -f CMakeFiles/generate-diagnostics.dir/build.make CMakeFiles/generate-diagnostics.dir/Tasks/GenerateDiagnostics.cpp.s
.PHONY : Tasks/GenerateDiagnostics.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... accept-baseline"
	@echo "... l10ns"
	@echo "... rebuild_cache"
	@echo "... run-tests"
	@echo "... generate-diagnostics"
	@echo "... find"
	@echo "... glob"
	@echo "... Source/Program/Exec.o"
	@echo "... Source/Program/Exec.i"
	@echo "... Source/Program/Exec.s"
	@echo "... Source/TestFramework/Exec.o"
	@echo "... Source/TestFramework/Exec.i"
	@echo "... Source/TestFramework/Exec.s"
	@echo "... Tasks/AcceptBaseline.o"
	@echo "... Tasks/AcceptBaseline.i"
	@echo "... Tasks/AcceptBaseline.s"
	@echo "... Tasks/GenerateDiagnostics.o"
	@echo "... Tasks/GenerateDiagnostics.i"
	@echo "... Tasks/GenerateDiagnostics.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

