/**
 * This file is generated by jsonrpcstub, DO NOT CHANGE IT MANUALLY!
 */

#ifndef JSONRPC_CPP_STUB_JSONRPCCLIENT_H_
#define JSONRPC_CPP_STUB_JSONRPCCLIENT_H_

#include <jsonrpccpp/client.h>

class JsonRpcClient : public jsonrpc::Client
{
    public:
        JsonRpcClient(jsonrpc::IClientConnector &conn, jsonrpc::clientVersion_t type = jsonrpc::JSONRPC_CLIENT_V2) : jsonrpc::Client(conn, type) {}

        Json::Value sync(const Json::Value& files, const Json::Value& function_names) throw (jsonrpc::JsonRpcException)
        {
            Json::Value p;
            p["files"] = files;
            p["function_names"] = function_names;
            Json::Value result = this->CallMethod("sync",p);
            if (result.isObject())
                return result;
            else
                throw jsonrpc::JsonRpcException(jsonrpc::Errors::ERROR_CLIENT_INVALID_RESPONSE, result.toStyledString());
        }
        void compile() throw (jsonrpc::JsonRpcException)
        {
            Json::Value p;
            p = Json::nullValue;
            this->CallNotification("compile",p);
        }
};

#endif //JSONRPC_CPP_STUB_JSONRPCCLIENT_H_
