/**
 * This file is generated by jsonrpcstub, DO NOT CHANGE IT MANUALLY!
 */

#ifndef JSONRPC_CPP_STUB_JSONRPCCLIENT_H_
#define JSONRPC_CPP_STUB_JSONRPCCLIENT_H_

#include <jsonrpccpp/client.h>

class JsonRpcClient : public jsonrpc::Client
{
    public:
        JsonRpcClient(jsonrpc::IClientConnector &conn, jsonrpc::clientVersion_t type = jsonrpc::JSONRPC_CLIENT_V2) : jsonrpc::Client(conn, type) {}

        void sync() throw (jsonrpc::JsonRpcException)
        {
            Json::Value p;
            p = Json::nullValue;
            this->CallNotification("sync",p);
        }
        void compile(const Json::Value& LocalizationString) throw (jsonrpc::JsonRpcException)
        {
            Json::Value p;
            p["LocalizationString"] = LocalizationString;
            this->CallNotification("compile",p);
        }
};

#endif //JSONRPC_CPP_STUB_JSONRPCCLIENT_H_
