#!/usr/bin/env sh

./node_modules/mocha/bin/mocha ./specifications/index.js --ignore-leaks --reporter spec
./node_modules/mocha/bin/mocha ./plugins/javascript/specifications/index.js --ignore-leaks --reporter spec --bail
